language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
before_script:
  - sudo apt-get install php5-sqlite
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-dist --no-interaction
script: phpunit --coverage-text tests
