language: php
php:
  - 5.2
  - 5.3
  - 5.4  
before_script:
  - sudo apt-get install php5-sqlite
  - pear channel-discover pear.doctrine-project.org
  - pear install doctrine/Doctrine
  - phpenv rehash
script: phpunit --configuration tests/phpunit.xml --coverage-text
