language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
before_script:
  - sudo apt-get install php5-sqlite
  - pear channel-discover pear.doctrine-project.org
  - pear install doctrine/Doctrine
  - phpenv rehash
script: phpunit --coverage-text tests
